### ISSUE TITLE
ProMods crashes with Proton 5.13

### ISSUE THREAD

**Issue by badlydrawnface** [truckersmp-cli/truckersmp-cli#147]
When I copied all the files and ran truckersmp-cli, It all loaded proper into the menu, but when I tried joining the Promods server in TMP online, the game crashed after I finished loading. Promods works perfectly fine in normal ETS2. Help?! (PM Canada works perfectly fine online)
**Update: After running with the verbose output, the game got to the truck before crashing immediately after**

Expected Behavior:
Game should have loaded and connected to server as usual.

OS:
Manjaro Linux 20.2.1
Proton version: Proton 5.13
truckersmp-cli version: 0.4.1

Commands: 
truckersmp-cli -d -a -p -s -u -x /home/bdface/.steam/steam/steamapps/compatdata/270880 -g /home/bdface/.steam/steam/steamapps/common/American\ Truck\ Simulator --activate-native-d3dcompiler-47 (ATS)

truckersmp-cli -d -p -s -u -x /home/bdface/.steam/steam/steamapps/compatdata/227300 -g /home/bdface/.steam/steam/steamapps/common/Euro\ Truck\ Simulator\ 2 --activate-native-d3dcompiler-47 (ETS2)

Terminal Output:
** INFO **  Proton output:
ERROR: ld.so: object '/home/bdface/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/bdface/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
pid 34335 != 34332, skipping destruction (fork without exec?)
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198282881997 [API loaded no]
wine: Unhandled page fault on execute access to 000000006ACC14C4 at address 000000006ACC14C4 (thread 0110), starting debugger...

Steps to reproduce:

1. Run the afformentioned ETS2 command, replacing "bdface" with your username, replacing the contents of -x with your prefix, and replacing the contents of -g with your game directory.
2. Sign in to TruckersMP
3. Select the "ProMods" server
4. After loading, hit drive.

**Comment by Lucki** [comment]
> Promods works perfectly fine in normal ETS2.

I assume you mean running with `--singleplayer`? If not please try that first.
Also please post the full log next time.

Unfortunately I don't own all DLCs so I can't tell if ProMods actually would work right now.

**Comment by badlydrawnface** [comment]
promods works in single player, launching from steam, and with `--singleplayer` 

Promods canada works perfectly fine online and offline on ATS

**Comment by badlydrawnface** [comment]
Some more output

This time, the game works for a few seconds from a garage outside of London, but crashes afterwards.

** INFO **  Proton output:
ERROR: ld.so: object '/home/bdface/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/bdface/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
fsync: up and running.
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198282881997 [API loaded no]
wine: Unhandled page fault on execute access to 000000006ACC14C4 at address 000000006ACC14C4 (thread 0110), starting debugger...
pid 54512 != 54511, skipping destruction (fork without exec?)

**Comment by Mar0xy** [comment]
Yeah, Promods does indeed crash the game when you are in the truck in fact depending on the hardware
you can actually see the game loaded and move atleast a few meters before it decides to crash or turn on the truck before it crashes.
I also tried Proton-GE but that has not resolved anything so I would assume it has something to do with TruckersMP itself

**Comment by JoohanV** [comment]
I also had this problem, but fixed it through switching back to Proton 5.0. Perhaps a TruckersMP update isn't compatible with a relatively new addition to Proton?

**Comment by badlydrawnface** [comment]
> Yeah, Promods does indeed crash the game when you are in the truck in fact depending on the hardware
> you can actually see the game loaded and move atleast a few meters before it decides to crash or turn on the truck before it crashes.
> I also tried Proton-GE but that has not resolved anything so I would assume it has something to do with TruckersMP itself.
> Which means its better to look at the game.log file to see why ETS2 decides to crash

Does this have any correlation with AMD GPUs?

**Comment by JoohanV** [comment]
No, it happened with my Nvidia GTX 970 as well.

**Comment by Lucki** [comment]
@badlydrawnface @JoohanV Please make an update to proton appid 1245040, try again and report back.
You can do this in one go with `truckersmp-cli --start --update --proton-appid 1245040` assuming you're using the default folders.

**Comment by JoohanV** [comment]
> I also had this problem, but fixed it through switching back to Proton 5.0. Perhaps a TruckersMP update isn't compatible with a relatively new addition to Proton?

@Lucki as I stated here I already did that, and it fixed the issue.

**Comment by Mar0xy** [comment]
> @badlydrawnface @Mar0xy Please make an update to proton appid 1245040, try again and report back.
> You can do this in one go with `truckersmp-cli --start --update --proton-appid 1245040` assuming you're using the default folders.

Exactly, like @JoohanV said Proton 5.0 seemed to fix the issue I think this should be added as a note in the readme

**Comment by kakurasan** [comment]
As of Feb 2021 TruckersMP mod is working with Proton 5.0 and I don't think we need Proton 5.13+ specific functionalities.
So I think that it's OK to set 5.0 to default again if this is Proton 5.13+ specific issue (I'm afraid that I cannot test ProMods because of not having map DLCs).

However, we (truckersmp-cli developers and users) have to keep in mind that Proton 5.0 may stop working in the future: [Proton 4.2 already stopped working](https://github.com/lhark/truckersmp-cli/issues/50#issuecomment-567029474).

**Comment by kallestrop** [comment]
At least you can manually update DXVK to the latest version by replacing the .dll files in both truckersmp-cli/Proton/dist/lib/wine/dxvk and truckersmp-cli/Proton/dist/lib64/wine/dxvk folders.

I tested Proton 5.0-10 with DXVK 1.8 on Promods server and it run stable.

You can find DXVK release at https://github.com/doitsujin/dxvk/releases/tag/v1.8

**Comment by kallestrop** [comment]
Yesterday Steam released Proton 6.3. It seems with this version ProMods works again. I was able to play on ProMods server without any crash.
