### ISSUE TITLE
Truckersmp don't launch

### ISSUE THREAD

**Issue by Junosik007** [truckersmp-cli/truckersmp-cli#152]
When i strarted truckermp-cli in console command: truckersmp-cli -n (STEAM NAME) start loging, verifi install... Then start Steam with 99 secounds countdown. After 99 secounds is nafing hapend and stop running. Unfortunately is dasn't throw any error.

This hapend when i try Choose native Steam installation manually.

## Expected behavior
I expect after start steam open truckersMP.exe winow and start game.

## Command
~~~
truckersmp-cli -n (STEAM NAME)
~~~

## Terminal output
![Screenshot_20210215_152243](https://user-images.githubusercontent.com/79095289/107958524-6bdd9180-6fa2-11eb-9f76-f658f4103e28.png)
~~~

## Information
 - OS: [e.g. Ubuntu 18.04 with KDE plasma 5.12.9]
 - Proton or Wine version: [e.g. `Proton 5.0-7`]
 - truckersmp-cli version: [e.g. `0.4.1`]

## Additional contex

**Comment by Lucki** [comment]
Thanks for the report but unfortunately you kind of ignored our precious issue template when creating this issue so I have to ask for additional information. Please run with additional debug output `-vv` and post the log in code tags.

**Comment by Junosik007** [comment]
Sorry I didnt know about the -vv command so there is my debug log, Thanks. 

![Screenshot_20210217_151410](https://user-images.githubusercontent.com/79095289/108216463-ce659780-7132-11eb-8ae2-308396f63c83.png)

I thought that problem may be in steam because I had steam in ~/.steam, but truckersmpp thought that i have it in ~/local/share/Steam but i couldn*t change it even if I run --steam-native-installation.

**Comment by Lucki** [comment]
Please test if this is still an issue with v0.5.0. Make sure you do an update after switching to the new version.

**Comment by Lucki** [comment]
Closing because lacking feedback.
