### ISSUE TITLE
Automatic branch detection has stopped working

### ISSUE THREAD

**Issue by Lucki** [truckersmp-cli/truckersmp-cli#162]
They've set some cloudflare javascript checking in front of their server.
We have to get the latest ets2/ats version numbers from somewhere else.

**Comment by kakurasan** [comment]
Working for me. `check_downgrade_needed()` got HTML code that contains `b'<h4>It&#039;s time to downgrade!</h4>\n'` and `determine_game_branch()` returned `temporary_1_39`.

**Comment by Lucki** [comment]
I'm getting:

~~~
** WARNING **  Failed to get content of TruckersMP Status page: HTTP Error 503: Service Temporarily Unavailable
** INFO **  Game branch: public
~~~

In Firefox I have to wait for cloudflares ddos protection to redirect me.

**Comment by kakurasan** [comment]
Can you get HTML code from `https://forum.truckersmp.com/`? The page has "It's time to downgrade!" link.

> ** WARNING **  Failed to get content of TruckersMP Status page: HTTP Error 503: Service Temporarily Unavailable

What happens if you retry?

**Comment by Lucki** [comment]
The forum works (at least for now):
~~~ html
$ http https://forum.truckersmp.com/ | grep downgrade
<a href='https://forum.truckersmp.com/index.php?/announcement/156-its-time-to-downgrade/' data-ipsDialog data-ipsDialog-title="It&#039;s time to downgrade!">It&#039;s time to downgrade!</a>
<li class='ipsDataItem_lastPoster__title'><a href="https://forum.truckersmp.com/index.php?/topic/103515-having-the-latest-version-of-ets2-and-the-downgraded-version-in-paralell/&amp;do=getNewComment" title='Having the latest Version of ETS2 and the Downgraded Version in paralell'>Having the latest Version of ETS2 and the Downgraded Version in paralell</a></li>
<a href='https://forum.truckersmp.com/index.php?/topic/103515-having-the-latest-version-of-ets2-and-the-downgraded-version-in-paralell/&amp;do=getLastComment' title='Go to last post'><time datetime='2021-03-30T21:56:55Z' title='03/30/21 09:56  PM' data-short='1 hr'>1 hour ago</time></a>
<a href='https://forum.truckersmp.com/index.php?/announcement/156-its-time-to-downgrade/' data-ipsDialog data-ipsDialog-title="It&#039;s time to downgrade!">It&#039;s time to downgrade!</a>
<a href="https://forum.truckersmp.com/index.php?/topic/103515-having-the-latest-version-of-ets2-and-the-downgraded-version-in-paralell/" title='View the topic Having the latest Version of ETS2 and the Downgraded Version in paralell' class='ipsDataItem_title'>Having the latest Version of ETS2 and the Downgraded Version in paralell</a>
~~~

> What happens if you retry?

It's all the time that cloudflare page when checked with httpie or 503 reported by our python.

**Comment by kakurasan** [comment]
> The forum works (at least for now):

Sorry, unfortunately the HTML code doesn't contain game names and we cannot use the page.

I would not like to maintain branch/version files (in our project) because:
* We (not TMP) need to maintain it
    * Not always synced with TMP site/mod -> This may introduce version issues
* Every user needs to access GitHub server when updating game

I think it's enough to:
* allow users to automatically determine branch name (`temporary_X_Y`) using `get_supported_game_versions()` and downgrade to the branch when updating *with new `--downgrade` option*
* add "How to downgrade" to README
