### ISSUE TITLE
Adding ETS2 launch parameter

### ISSUE THREAD

**Issue by kallestrop** [truckersmp-cli/truckersmp-cli#163]
Hello,

Is it possible to add a launch option like in the Steam Game properties? In my case I need a "-sysmouse" otherwise I don't have a mouse pointer on the desktop after ALT-TAB out of the game.

**Comment by kakurasan** [comment]
Currently ETS2/ATS options are hardcoded:
* Multiplayer: `main()` [`truckersmp-cli.c`]
    * `const char opts[] = "-nointro -64bit";`
* Singleplayer: `start_with_proton()` [`truckersmp_cli/main.py`]
    * `argv += gamepath, "-nointro", "-64bit"`

If we need to allow to use other options, we need to:
* add new option (`e.g. --game-options="-option1 -option2 ..."`) to our Python script
* add command line options handling to `truckersmp-cli.c`

An example of command line options handling for our inject program:
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define BUF_SIZE 1024

int
main(int argc, char **argv)
{
    int i;
    char opts[BUF_SIZE] = {0};

    if (argc < 3) {
        fprintf(stderr, "Usage: truckersmp-cli GAMEDIR MODDIR, GAME_OPTIONS...\n");
        return EXIT_FAILURE;
    }

    if (argc == 3)
        strcpy(opts, " -nointro -64bit");

    for (i = 3; i < argc; i++) {
        strcat(opts, " ");
        strcat(opts, argv[i]);
    }

    printf("options: \"%s\"\n", opts);

    return EXIT_SUCCESS;
}
```

```
(Too few arguments)
$ ./opttest
Usage: truckersmp-cli GAMEDIR MODDIR, GAME_OPTIONS...

(Use default options)
$ ./opttest /path/to/game /path/to/mod
opts: " -nointro -64bit"

(Use custom options)
$ ./opttest /path/to/game /path/to/mod -nointro -64bit -sysmouse
opts: " -nointro -64bit -sysmouse"
```

As a workaround, users can edit the hardcoded options, compile `truckersmp-cli.c`, and replace original `truckersmp-cli.exe` with compiled executable.

**Comment by kallestrop** [comment]
Thanks for the advice of workaround. I compiled truckersmp-cli.exe with the additional launch option and it works. 

It would be nice to have an option for ETS2/ATS specific launch parameter in a newer version of truckersmp-cli, because there are some useful options to tweak performance a bit like "-mm_max_resource_size" or "-mm_max_tmp_buffers_size".
