### ISSUE TITLE
TruckersMP Installation

### ISSUE THREAD

**Issue by TheRealDarkn3ss** [truckersmp-cli/truckersmp-cli#172]
First of all, the installation. I don't know really how to do it, i'm a newbie right here.
The other problem, the ETS2 Steam installation. I have the game in "home\steam\SteamApps\common\Euro Truck Simulator 2", do I have to change the game to another folder to truckersmp-cli folder or something? I'm so newbie in Linux, thanks.

**Comment by Lucki** [comment]
Steam will download the linux files which you don't need.
This should get you going: https://github.com/truckersmp-cli/truckersmp-cli#everything-default

**Comment by TheRealDarkn3ss** [comment]
> Steam will download the linux files which you don't need.
> This should get you going: https://github.com/truckersmp-cli/truckersmp-cli#everything-default

Ok, let me check that.

**Comment by TheRealDarkn3ss** [comment]
Now here comes the other problem, it seems everything is fine "$HOME/.local/bin", there is a truckersmp-cli file, I downloaded the repository and then in Terminal make it, but when I put "cp truckersmp-cli.bash "${XDG_DATA_HOME:-~/.local/share}/bash-completion/completions/truckersmp-cli"" command, just says that "cp: cannot perform `stat 'on' truckersmp-cli.bash ': File or directory does not exist"

**Comment by Lucki** [comment]
Please look in the readme for recommended ways to install this script: https://github.com/truckersmp-cli/truckersmp-cli#install
If you still want to build it by yourself (you really shouldn't as "I'm so newbie in Linux, thanks.") make sure you follow the build steps closely: https://github.com/truckersmp-cli/truckersmp-cli#build
Hint: satisfy the build requirements

**Comment by TheRealDarkn3ss** [comment]
> Please look in the readme for recommended ways to install this script: https://github.com/truckersmp-cli/truckersmp-cli#install
> If you still want to build it by yourself (you really shouldn't as "I'm so newbie in Linux, thanks.") make sure you follow the build steps closely: https://github.com/truckersmp-cli/truckersmp-cli#build
> Because that's the dev route it's missing some basic stuff like adding paths to your `$PATH` (**hint**).
> The error implies you're missing some optional build requirements.

It worked already friend, seriously, thank you very much, and if it was what you said, I was missing some tools, so I will proceed to close the post.

**Comment by TheRealDarkn3ss** [comment]
Hey, I just reopened the post, because I get this error, as I see, that app makes reference to Proton 5.0, so I wanna know what I'm doing incorrectly, maybe is the most simple solution, maybe not.
![image](https://user-images.githubusercontent.com/64052522/115317791-faf15c00-a141-11eb-8c01-1f81b4b7509c.png)

**Comment by TheRealDarkn3ss** [comment]
Nevermind, now the solution was reinstall everything, btw, thanks all :+1:
