### ISSUE TITLE
pressure-vessel-wrap: W: Binding directories that are located under "/usr/" is not supported

### ISSUE THREAD

**Issue by Klairm** [truckersmp-cli/truckersmp-cli#197]
## Describe the bug
Tried to start the game but getting that error seems like a file is missing I already tried to reinstall truckersmp-cli but got the same error

## Expected behavior
Run the game correctly

## Command
~~~
truckersmp-cli start ets2mp  -v

~~~

## Terminal output
<details><summary>Collapsed log</summary>

~~~
** INFO **  Mod directory: /home/ivan/.local/share/truckersmp-cli/TruckersMP
** INFO **  Platform is Linux, using Proton
** INFO **  AppID/GameID: 227300 (ets2)
** INFO **  Game directory: /home/ivan/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
** INFO **  Prefix: /home/ivan/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
** INFO **  Proton directory: /home/ivan/.local/share/truckersmp-cli/Proton
** INFO **  Steam Runtime directory: /home/ivan/.local/share/truckersmp-cli/SteamRuntime
                                                                      
** INFO **  Steam installation directory: /home/ivan/.local/share/Steam
** INFO **  Proton version is (major=6, minor=3)
** INFO **  Using Steam Runtime container
** INFO **  Running Steam Runtime helper:
  SteamAppId=227300
  SteamGameId=227300
  LD_PRELOAD=/home/ivan/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
  PROTON_NO_D3D11=1
  PROTON_USE_WINED3D=0
  STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/ivan/.local/share/Steam
  STEAM_COMPAT_DATA_PATH=/home/ivan/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
  python3
    /home/ivan/.local/share/truckersmp-cli/Proton/proton
    run
    /usr/lib/python3.9/site-packages/truckersmp_cli/truckersmp-cli.exe
    /home/ivan/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
    /home/ivan/.local/share/truckersmp-cli/TruckersMP
    -nointro
    -64bit
pressure-vessel-wrap[31505]: W: Binding directories that are located under "/usr/" is not supported!
python3: can't open file '/usr/lib/python3.9/site-packages/truckersmp_cli/steamruntime_helper.py': [Errno 2] No such file or directory

~~~
</details>

## Screenshots
<details><summary>Collapsed screenshots</summary>

![imagen](https://user-images.githubusercontent.com/40839469/122252603-c7297d00-cecb-11eb-8934-ec3b62c29e35.png)

</details>

## Information
 - OS: [Arch Linux]
 - Proton or Wine version: [ `Proton 6.0.3`]
 - truckersmp-cli version: [lastest]

**Comment by Lucki** [comment]
@kakurasan That's from the system installation. We may need to copy them into user space temporarily.

**Comment by Klairm** [comment]
And what could I do to play the game?

**Comment by Klairm** [comment]
> And what could I do to play the game?
I downloaded the release version and it executes but I get like 3 fps

**Comment by Klairm** [comment]
> > And what could I do to play the game?
> > I downloaded the release version and it executes but I get like 3 fps

So if I use `--enable-d3d11` it will get better fps, but can't connect to truckersMP for some reasons

**Comment by Lucki** [comment]
> can't connect to truckersMP for some reasons

https://github.com/truckersmp-cli/truckersmp-cli#known-issues
