### ISSUE TITLE
truckersmp-cli does not start using wine prefix inside lutris

### ISSUE THREAD

**Issue by Kazenin** [truckersmp-cli/truckersmp-cli#206]
I am trying to start atsmp or etsmp using this command:

`./truckersmp-cli --wine --prefixdir "path/to/prefix" --wine-steam-dir "C:\Program Files (x86)\Steam" start atsmp`

Lutris is open and Winesteam is running. what could I be doing wrong?

**Comment by Lucki** [comment]
Thanks for opening this bug report.
Unfortunately you ignored our precious issue template when creating this issue so I have to ask for additional information. Please fill out the issue template. You can find the latest issue template here: https://raw.githubusercontent.com/lhark/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Lucki** [comment]
Closing because lacking feedback.
