### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by krzysdymowski** [truckersmp-cli/truckersmp-cli#210]
After entering the command, nothing is displayed or Writes wait 90 seconds and then nothing.

**Comment by krzysdymowski** [comment]
help

**Comment by JoohanV** [comment]
Could you please tell more about what exactly it is you are doing? A good start would be to fill out the issue template: https://raw.githubusercontent.com/lhark/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by krzysdymowski** [comment]
I am stunned. After adding -v, the game suddenly started. No help needed anymore. The Steam client was updating today. Maybe it was Steam's fault.
