### ISSUE TITLE
truckersmp-cli: command not found

### ISSUE THREAD

**Issue by klospk** [truckersmp-cli/truckersmp-cli#215]
as a linux newbie i tried to do as much as i can without needing anybody,i failed

## Describe the bug
i did every code on installation page,still having error
## Expected behavior
the game to open itself

## Command
~~~
truckersmp-cli -w start ets2mp
~~~

## Terminal output
truckersmp-cli: command not found

~~~
Replace this line with the terminal output you're getting
when running the command with debug output [-vv]
~~~
</details>

## Screenshots
<details><summary>Collapsed screenshots</summary>

[comment]: # (If applicable, add screenshots to help explain your problem:)

</details>

## Information
 - OS: [e.g. Ubuntu 21.04, pop!_os]

**Comment by kakurasan** [comment]
> as a linux newbie i tried ... failed

If you installed via [pip](https://github.com/truckersmp-cli/truckersmp-cli#python-package-index) with `--user` option, check whether `~/.local/bin/truckersmp-cli --version` works.

> Make sure the binary path (e.g. `$HOME/.local/bin`) is in your `$PATH`.

If it works, try adding `~/.local/bin` to your environment variable `PATH`.

If you're using bash, add the following line to your `~/.bashrc` and re-login:

```sh
export PATH=$PATH:~/.local/bin
```

**Comment by klospk** [comment]
i think the problem was the fact that i needed to reboot,it works now
