### ISSUE TITLE
Game stutters and becomes unplayable

### ISSUE THREAD

**Issue by lus** [truckersmp-cli/truckersmp-cli#220]
Hello.
I currently have the problem that my game stutters and becomes nearly unplayable.
I read the reviews here and on ProtonDB and nearly everyone says that the game should run better, but at least equally good compared to running it on Windows.
Back when I used Windows I could play the game on medium settings without any lags, but now that won't work.
The most strange thing is that the stuttering does not change if I switch to low graphic settings so I think the graphic settings are not the issue.

First of all, I tried starting it using `truckersmp-cli -g ~/.steam/steam/steamapps/common/Euro\ Truck\ Simulator\ 2 -p -v start` (just bare Proton) and it was completely unplayable due to lags.
Then I switched to DirectX 11 using `truckersmp-cli -g ~/.steam/steam/steamapps/common/Euro\ Truck\ Simulator\ 2 -p -v -d start` and the game didn't start at all.
I enabled the native compiler and the game started an ran a bit better than on OpenGL (I was expecting that).
Enabling WineD3D (`truckersmp-cli -g ~/.steam/steam/steamapps/common/Euro\ Truck\ Simulator\ 2 -p -v -d --use-wined3d start`) made the game just a bit better and it seems to run flawless in medium settings, but there is weird stuttering that makes it unplayable.

I hope anyone can give me advise on how to fix that if possible.

OS: Arch Linux x64
CPU/GPU: AMD Ryzen 3 2200G (Vega 8 graphics included)
Ram: 8GB

(Yeah, I know, pretty bad setup, but definitely ran the game flawlessly on Windows 10)

**Comment by Lucki** [comment]
Please check if the game also stutters when the compiler message isn't displayed in the lower left running the following with dxvk:

~~~
DXVK_HUD=compiler truckersmp-cli …
~~~

**Comment by lus** [comment]
This environment variable actually improves the performance a bit, but it still isn't comparable to Windows.

**Comment by Lucki** [comment]
Shader compiling takes time and is done for every new shader you encounter. And while the task is done on the fly it causes major stutters by doing so. The variable tells you if that compiling is still going on. So please verify the performance *after* the "Compiling shader…" message in the lower left isn't visible anymore.

**Comment by lus** [comment]
Oh, well, there was no message in the lower left...

**Comment by Lucki** [comment]
Then that's not it ;)

Maybe a demanding task is running in the background? Firefox with a video running, Steam background shader compiling, … just some wild guesses.

**Comment by lus** [comment]
Nope, nothing like that. Restarting my machine and not starting anything doesn't change something about that.
As I think Steam would tell me that it compiles shaders in some way (progress bar, idk) I think I can exclude that too.

**Comment by lus** [comment]
Alright, my fix was setting up a Linux & Windows dual boot environment to have general-purpose workspace and gaming stuff separated.
I will close this issue as I won't be able to try out other solutions.
Thanks for your help.
