### ISSUE TITLE
[WINE] Odd window steam issues

### ISSUE THREAD

**Issue by XylonWasTaken** [truckersmp-cli/truckersmp-cli#257]
# This is the step by step on how I set up wine for truckersmp

## Making the wineprefix and data folders.
`mkdir ~/Games/ets2`
`mkdir ~/Games/ets2/data` - for game data
`mkdir ~/Games/ets2/pfx` - for prefix

## Setting up and installing necessary stuff
`export WINEARCH=win64` then `export WINEPREFIX=~/Games/ets2/pfx`
`winetricks steam` and then `winetricks steam`
Both did not give any errors and I logged in to my account on Steam
`wineserver -k` for good measures

## Command & Error
`truckersmp-cli -w -g "/home/xylon/Games/ets2/data" -x "/home/xylon/Games/ets2/pfx/" start ets2mp`
ETS2 got downloaded and it tried to run the windows Steam but instead gave out an error (Image below)

![image](https://user-images.githubusercontent.com/76113285/143187504-e8eb6dc7-a423-46a6-aa44-40becb29cd8e.png)

I ran `wine taskmgr` inside of the prefix and killed the steam processes (and I left it running in the bg) reran the truckersmp-cli command, and steam ran but with 3 exceptions
1. it can't connect to Steam and I would have to kill wineserver.
2. If it WAS able to connect to steam then it would prompt me to install ETS2 again. (huh?)
3. AND if somehow it was able to run ETS2 it would use the resolution 2560x1600 which my monitor really doesn't like and would just return [Input not supported] (I added `--game-options="-nointro -64bit -screen-width 1920 -screen-height 1080"` BUT still used the same resolution instead of 1920x1080)

## Information
 - OS: Arch Linux
 - Kernel: 5.15.4-zen1-1-zen
 - Proton or Wine version: Wine 6.21 TKG Staging
 - truckersmp-cli version: 0.7.3

**Comment by kakurasan** [comment]
I don't recommend to use development versions of Wine because they often have issues related to Windows version of Steam client. (Note: Such bugs should be reported to Wine Bugzilla)

Since we support Proton, Linux users don't need to suffer from Windows Steam issues.

As of 1.42, ETS2 and ATS don't require recent (unstable/experimental) Wine/Proton and probably you don't need to use the version.

**Comment by XylonWasTaken** [comment]
I actually manage to make steam work although I have to run an app in the background for it to not give out.  TMP works perfectly but the only problem is that the game uses the resolution 2560x1600 although I set it through --game-options and at the game profile. The only workaround that I found is to use a virtual desktop and set it to 1920x1080.

This question is unrelated but do you know any alternatives to [ets2-telemetry-server](https://github.com/Funbit/ets2-telemetry-server)? I am trying to log jobs and etc since I've tried Truckersbook.eu but wasn't able to make it work.

**Comment by kakurasan** [comment]
> the only problem is that the game uses the resolution 2560x1600 although I set it through --game-options and at the game profile.

I guess the resolution stuff is `winex11` issue in Wine/Proton (might be game issue...?). Our software is a launcher and we cannot fix it.

> The only workaround that I found is to use a virtual desktop and set it to 1920x1080.

Though our virtual desktop support (`--wine-desktop` option) was added for issue #90 which is already fixed, it's useful to work around resolution issue and we continue to support it.

> do you know any alternatives to ets2-telemetry-server?

See/move to #157.
