### ISSUE TITLE
Truckersmp-cli not starting

### ISSUE THREAD

**Issue by Felix-Brunner** [truckersmp-cli/truckersmp-cli#284]
## Describe the bug
If I try to execute `truckersmp-cli start ets2mp`, it shows "Waiting x seconds for steam to start up". Then Steam (Store) opens, the message in the terminal disappears and nothing happens (the game doesn't start). The command seams do be done executing.  Even if i try it with `truckersmp-cli start ets2` the same thing happens. I already tried `truckersmp-cli update ets2mp`. Everything seams to be normal. This command ends with a success after verifying all game files.

## Expected behavior
ETS2MP/ETS2 should start

## Command
~~~
truckersmp-cli start ets2mp
~~~

## Terminal output

~~~
There is no Terminal output
~~~
</details>

## Screenshots
<details><summary>Collapsed screenshots</summary>

![truckersmp_bug](https://user-images.githubusercontent.com/72706974/148997375-173cb915-17d6-4541-b74d-abd7dfb81e8c.png)

</details>

## Information
 - OS: Linux Mint 19.3 Cinnamon (Based on Ubuntu 18.04 LTS)
 - Proton or Wine version: Proton-6.3-8c
 - truckersmp-cli version: 0.8.1

**Comment by Lucki** [comment]
Please update to 0.8.2 and run with `-vv`.

**Comment by kakurasan** [comment]
I guess this is what we fixed in 0.8.2 (PR 280 and 282): Please update to 0.8.2 *or* run with `-v` or `-vv`.

If this is not the case, please reopen this.

**Comment by Felix-Brunner** [comment]
Thank you very much, it is working now!
Have a nice day!
