### ISSUE TITLE
Connection refused: You are not the owner of some DLC you use.

### ISSUE THREAD

**Issue by P50ACA** [truckersmp-cli/truckersmp-cli#314]
Whenever I try to join a truckersmp server, I get this error
![Screenshot from 2022-08-24 12-50-56](https://user-images.githubusercontent.com/57576932/186501148-67ffe3e1-e87b-4e3c-9a28-34c2b818b228.png)

Here is a list of all of the DLC's I own and use:
![image](https://user-images.githubusercontent.com/57576932/186501347-2b859760-d7b8-4bc9-abfd-d5805cdc5b66.png)
![image](https://user-images.githubusercontent.com/57576932/186501424-ff400359-530f-4248-8f95-cab32b7dd2ef.png)
![image](https://user-images.githubusercontent.com/57576932/186501474-bb62712c-0c13-4ad3-bc57-de4656c9a127.png)

My operating system is Ubuntu 22.04 LTS and I am using the 5.15.0-46-generic kernel.

**Comment by Lucki** [comment]
Recheck your DLCs at https://truckersmp.com/profile/settings
