### ISSUE TITLE
Game wont launch

### ISSUE THREAD

**Issue by ibndiaye** [truckersmp-cli/truckersmp-cli#315]
---
name: Game wont launch
---

## Describe the bug
If i run the game with my launch commands below or with the defaults "truckersmp-cli start ets2mp" it gives me the same output.

## Expected behavior
I expect the game to open its windows, connect the discord RPC and launch TMP.

## Command
~~~
tmpets='gamemoderun mangohud truckersmp-cli --disable-steamruntime --rendering-backend dx11 --proton --game-options="-nointro" -vv start ets2mp'
~~~

## Terminal output
~~~
gamemodeauto: 
gamemodeauto: 
** INFO **  Log file: <empty> (Default)
** INFO **  Game directory: /home/brams/.local/share/truckersmp-cli/Euro Truck Simulator 2/data (Default)
** INFO **  Prefix directory: /home/brams/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix (Default)
** INFO **  Game options: -nointro (Command line option)
** INFO **  TruckersMP MOD directory: /home/brams/.local/share/truckersmp-cli/TruckersMP (Default)
** INFO **  Whether to disable Steam Runtime (deprecated): False (Default)
** INFO **  Whether to disable Steam Runtime: True (Command line option)
** INFO **  Whether to use Flatpak version of Steam: False (Default)
** INFO **  Whether to disable Steam Overlay: False (Default)
** INFO **  Proton directory: /home/brams/.local/share/truckersmp-cli/Proton (Default)
** INFO **  Steam Runtime directory: /home/brams/.local/share/truckersmp-cli/SteamRuntime (Default)
** INFO **  Rendering backend: dx11 (Command line option)
** INFO **  AppID/GameID: 227300 (ets2)
** DEBUG **  Updating mod files
** DEBUG **  Creating directory /home/brams/.local/share/truckersmp-cli/TruckersMP if it doesn't exist
** DEBUG **  No files to download
~~~
</details>

## Screenshots
Stays stuck on this
![image](https://user-images.githubusercontent.com/63436162/195110239-45730794-afc3-4458-b81b-4fa907b40ed3.png)

</details>

## Information
 - OS: EndeavourOS (Arch based)
 - Proton or Wine version: `Proton 7.0.4 `
 - truckersmp-cli version: 0.9.1.1-1 from the AUR

**Comment by Lucki** [comment]
Please post your *correct* starting command and post logs as text. We have a template for this but unfortunately you ignored it when creating this issue so I have to ask for additional information. Please fill out the issue template. You can find the latest issue template here: https://raw.githubusercontent.com/truckersmp-cli/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ibndiaye** [comment]
> Please post your _correct_ starting command and post logs as text. We have a template for this but unfortunately you ignored it when creating this issue so I have to ask for additional information. Please fill out the issue template. You can find the latest issue template here: https://raw.githubusercontent.com/truckersmp-cli/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

My apologies, i have updated the issue

**Comment by ibndiaye** [comment]
Seems like it resolved now without doing anything
