### ISSUE TITLE
Setting Proton directory to one installed by Steam, causes the game to not launch properly

### ISSUE THREAD

**Issue by Tarballwalf** [truckersmp-cli/truckersmp-cli#322]
[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
Setting Proton directory to one installed by Steam, causes the game to not launch with the `start` option. 

## Expected behavior
Game should start up normally.

## Command
~~~
gamemoderun truckersmp-cli start
~~~

## Terminal output
<details><summary>Collapsed log</summary>

~~~
** INFO **  Platform is Linux, using Proton
** INFO **  Log file: <empty> (Default)
** INFO **  Game directory: /home/tarballwalf/.local/share/truckersmp-cli/Euro Truck Simulator 2/data (Default)
** INFO **  Prefix directory: /home/tarballwalf/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix (Default)
** INFO **  Game options: -nointro -64bit (Configuration file)
** INFO **  TruckersMP MOD directory: /home/tarballwalf/.local/share/truckersmp-cli/TruckersMP (Default)
** INFO **  Whether to disable Steam Runtime (deprecated): False (Default)
** INFO **  Whether to disable Steam Runtime: False (Default)
** INFO **  Whether to use Flatpak version of Steam: False (Default)
** INFO **  Whether to disable Steam Overlay: False (Configuration file)
** INFO **  Proton directory: /home/tarballwalf/.local/share/Steam/steamapps/common/Proton - Experimental/ (Configuration file)
** INFO **  Steam Runtime directory: /home/tarballwalf/.local/share/truckersmp-cli/SteamRuntime (Default)
** INFO **  Rendering backend: gl (Configuration file)
** INFO **  AppID/GameID: 227300 (ets2)
** DEBUG **  Updating mod files
** DEBUG **  Creating directory /home/tarballwalf/.local/share/truckersmp-cli/TruckersMP if it doesn't exist
** DEBUG **  No files to download
Traceback (most recent call last):
  File "/usr/bin/truckersmp-cli", line 19, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/truckersmp_cli/main.py", line 178, in main
    starter = StarterProton(cfg) if Args.proton else StarterWine(cfg)
  File "/usr/lib/python3.10/site-packages/truckersmp_cli/gamestarter.py", line 50, in __init__
    major, minor = get_proton_version(Args.protondir)
  File "/usr/lib/python3.10/site-packages/truckersmp_cli/utils.py", line 328, in get_proton_version
    major, minor = ver[ver.index(" ") + 1:ver.index("-")].split(".")
ValueError: not enough values to unpack (expected 2, got 1)
~~~
</details>

## Config File
<details><summary>Collapsed file</summary>

~~~
# Common settings
# Game mode specific sections are needed too to apply these settings
[DEFAULT]
rendering-backend = gl
# Use unofficial version of Proton in all games
proton-directory = /home/tarballwalf/.local/share/Steam/steamapps/common/Proton - Experimental/
# Disable Steam overlay
disable-proton-overlay = false

[ets2mp]
# Steam prefix directory
# prefix-directory = /steam/dir
# Steam game directory
# game-directory = /home/tarballwalf/.local/share/Steam/steamapps/common/Euro Truck Simulator 2/
# Custom game options
game-options = -nointro -64bit
~~~
</details>

## Information
 - OS: Manjaro
 - Proton or Wine version: Valve Proton Experimental
 - truckersmp-cli version: 0.9.1.1

## Additional context
Running the game first, with `truckersmp-cli update` fixes the issue temporarily, allowing `truckersmp-cli start` to work as expected.

**Comment by Lucki** [comment]
Example version string for Proton Experimental in the Bleeding Edge Beta branch:
`1668531248 experimental-bleeding-edge-7.0-29091-20221115-p02d7b6-w8dabf3-d785bc9-v8c4f29`

https://github.com/truckersmp-cli/truckersmp-cli/blob/757401dc7a647276a78907b9ae762fc276995f9b/truckersmp_cli/utils.py#L324-L348

**Comment by PadowYT2** [comment]
I get the same error with `truckersmp-cli start ets2mp --gamedir "/media/padow/sea/SteamLibrary/steamapps/common/Euro Truck Simulator 2" --protondir "/home/padow/.steam/root/compatibilitytools.d/GE-Proton7-50" --disable-steamruntime`

**Comment by kakurasan** [comment]
> I get the same error with `truckersmp-cli start ets2mp --gamedir "/media/padow/sea/SteamLibrary/steamapps/common/Euro Truck Simulator 2" --protondir "/home/padow/.steam/root/compatibilitytools.d/GE-Proton7-50" --disable-steamruntime`

Fixed in `GE-Proton7-51`: The version string in `GE-Proton7-50/version` is broken (`=` is used instead of `-`).

```
$ cat GE-Proton7-50/version
1678093712 GE=Proton7-50

$ cat GE-Proton7-51/version
1678925217 GE-Proton7-51
```

I don't think that we need a workaround for `GE-Proton7-50`.
