### ISSUE TITLE
Parental control issue

### ISSUE THREAD

**Issue by ExpandingShapes** [truckersmp-cli/truckersmp-cli#328]
[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
I have parental control on my account. When I try to update a game with the following command, truckersmp-cli fails to.

## Expected behavior
Update a desired game.

## Command
~~~
truckersmp-cli update ets2mp

~~~

## Terminal output
<details><summary>Collapsed log</summary>

~~~
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1675997306
-- type 'quit' to exit --
Loading Steam API...OK
Logging in user %MY_STEAM_USERNAME% to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
ERROR! Failed to install app '1887720' (Parental control blocked)
SteamCMD exited abnormally
~~~
</details>

## Information
 - OS:  Ubuntu 22.10
 - Proton or Wine version: Proton 7.0-6
 - truckersmp-cli version: 0.9.1.1

## Additional context
It would be great to ask for Family View password (if Steam API allows that)

**Comment by Lucki** [comment]
We don't do anything special with steam logins, this is all handled by SteamCMD itself.

Sadly I don't see anything meaningful in regards to this error:
* https://old.reddit.com/r/SteamCMD/comments/m7bfga/anybody_know_how_to_enter_parental_unlock_code_in/
* [`@bRequireSignedParentalSettings`](https://developer.valvesoftware.com/wiki/Command_Line_Options)
  > If true, a valid set of signed parental settings is required when logging in in offline or no connection mode
* [`@nParentalSettingsLogLevel`](https://developer.valvesoftware.com/wiki/Command_Line_Options)
  > Control the amount of spew written to the parental log file 

The log could include something interesting altough I doubt that. If you feel adventurous you can try to play around with the log levels and see if there's more log output somewhere. `4` is the default - my guess is that `0` is everything?

https://github.com/truckersmp-cli/truckersmp-cli/blob/d44037cbf090dc7430ed93f9c9ed1b4af908e918/truckersmp_cli/steamcmd.py#L123-L131

~~~ diff
 steamcmd.run( 
     [ 
+        "+@nParentalSettingsLogLevel", %LOG_LEVEL%,
         "+@sSteamCmdForcePlatformType", "windows", 
         "+force_install_dir", gamedir, 
         "+login", Args.account, 
         "+app_update", Args.steamid, "-beta", branch, "validate", 
         "+quit", 
     ] 
 ) 
~~~

**Comment by ExpandingShapes** [comment]
I see. Thanks for replying quickly.
So it's a SteamCMD issue and we can't do anything about it. According to the Reddit thread and what I faced with the bug is still unfixed.
I'm closing this issue then. Thank you for your work. ❤️
