### ISSUE TITLE
Game crashes and is laggy

### ISSUE THREAD

**Issue by Ftamino** [truckersmp-cli/truckersmp-cli#332]
So when I start the game with "truckersmp-cli --flatpak-steam  start ets2mp" It loads fine until you get to the login screen where the mouse moves very laggy. This is also the case for the next screens. Then when I join I can see the chat and hear voice until it fully loads and gives me this error:
![zk2zFE5](https://user-images.githubusercontent.com/83065176/233808938-b1f2fada-a9a7-41e0-ad81-b03cd8532a1f.png)

**Comment by Lucki** [comment]
Unfortunately you ignored our precious issue template when creating this issue so I have to ask for additional information. Please fill out the issue template. You can find the latest issue template here: https://raw.githubusercontent.com/lhark/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

Additionally add the relevant game logs: https://github.com/truckersmp-cli/truckersmp-cli#game-logs

**Comment by Ftamino** [comment]
It got fixed after updating steam and switching away from flatpak
