### ISSUE TITLE
Steam Client unaccesable after ets2mp update

### ISSUE THREAD

**Issue by FQQD** [truckersmp-cli/truckersmp-cli#335]
## Describe the bug
After TruckersMP Update using `truckersmp-cli update ets2mp -n FQQD` it doesn't recognize the steam client and gives error, worked fine before update

## Expected behavior
TruckersMP starting normally without any errors

## Command
~~~
`truckersmp-cli start ets2mp --rendering-backend dx11 -vv`
~~~

## Terminal output
<details><summary>Collapsed log</summary>

~~~
❯ truckersmp-cli start ets2mp --rendering-backend dx11 -vv
** INFO **  Platform is Linux, using Proton
** INFO **  Log file: <empty> (Default)
** INFO **  Game directory: /home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/data (Default)
** INFO **  Prefix directory: /home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix (Default)
** INFO **  Game options: -nointro -64bit (Default)
** INFO **  TruckersMP MOD directory: /home/fqqd/.local/share/truckersmp-cli/TruckersMP (Default)
** INFO **  Whether to disable Steam Runtime (deprecated): False (Default)
** INFO **  Whether to disable Steam Runtime: False (Default)
** INFO **  Whether to use Flatpak version of Steam: False (Default)
** INFO **  Whether to disable Steam Overlay: False (Default)
** INFO **  Proton directory: /home/fqqd/.local/share/truckersmp-cli/Proton (Default)
** INFO **  Steam Runtime directory: /home/fqqd/.local/share/truckersmp-cli/SteamRuntime (Default)
** INFO **  Rendering backend: dx11 (Command line option)
** INFO **  AppID/GameID: 227300 (ets2)
** DEBUG **  Updating mod files
** DEBUG **  Creating directory /home/fqqd/.local/share/truckersmp-cli/TruckersMP if it doesn't exist
** DEBUG **  No files to download
** INFO **  Proton version is (major=7, minor=0)
** INFO **  Using Steam Runtime container
** DEBUG **  Starting game with Proton
** DEBUG **  Starting Steam...
                                                                      
** DEBUG **  Steam should now be up and running and the user logged in.
** INFO **  Steam installation directory: /home/fqqd/.local/share/Steam
** DEBUG **  Creating directory /home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix if it doesn't exist
** DEBUG **  Shared paths: ['/home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/data', '/home/fqqd/.local/share/truckersmp-cli/Proton', '/home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix', '/home/fqqd/.local/share/truckersmp-cli', '/home/fqqd/.local/share/truckersmp-cli/TruckersMP', '/home/fqqd/.local/lib/python3.11/site-packages/truckersmp_cli', '/run/user/1000/discord-ipc-0']
** DEBUG **  Native d3dcompiler_47.dll is found
** DEBUG **  Failed to get Proton prefix version from version file
** DEBUG **  Whether to setup native d3dcompiler_47: True
** DEBUG **  d3dcompiler_47.dll is present, MD5 is OK.
** DEBUG **  Copying d3dcompiler_47.dll into /home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/dosdevices/c:/windows/system32
** DEBUG **  Adding DLL override setting for eurotrucks2.exe
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
reg: The operation completed successfully
** INFO **  Running Steam Runtime helper:
  SteamAppId=227300
  SteamGameId=227300
  LD_PRELOAD=/home/fqqd/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
  PROTON_USE_WINED3D=0
  STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/fqqd/.local/share/Steam
  STEAM_COMPAT_DATA_PATH=/home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
  python3
    /home/fqqd/.local/share/truckersmp-cli/Proton/proton
    run
    /home/fqqd/.local/lib/python3.11/site-packages/truckersmp_cli/truckersmp-cli.exe
    /home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
    /home/fqqd/.local/share/truckersmp-cli/TruckersMP
      -rdevice dx11 -nointro -64bit
** DEBUG **  winediscordipcbridge.exe is present, MD5 is OK.
** DEBUG **  Helper arguments: ['/home/fqqd/.local/share/truckersmp-cli/SteamRuntime/run', '--filesystem', '/home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/data', '--filesystem', '/home/fqqd/.local/share/truckersmp-cli/Proton', '--filesystem', '/home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix', '--filesystem', '/home/fqqd/.local/share/truckersmp-cli', '--filesystem', '/home/fqqd/.local/share/truckersmp-cli/TruckersMP', '--filesystem', '/home/fqqd/.local/lib/python3.11/site-packages/truckersmp_cli', '--filesystem', '/run/user/1000/discord-ipc-0', '--', 'python3', '/home/fqqd/.local/lib/python3.11/site-packages/truckersmp_cli/steamruntime_helper.py', '--early-executable', '/home/fqqd/.local/share/truckersmp-cli/wine-discord-ipc-bridge/winediscordipcbridge.exe', '--early-wait-before-start', '5', '--wait-before-start', '0', '-vv', '--', 'python3', '/home/fqqd/.local/share/truckersmp-cli/Proton/proton', 'run', '/home/fqqd/.local/lib/python3.11/site-packages/truckersmp_cli/truckersmp-cli.exe', '/home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/data', '/home/fqqd/.local/share/truckersmp-cli/TruckersMP', '-rdevice', 'dx11', '-nointro', '-64bit']
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561199263902977 [API loaded no]
Executables (early): ['/home/fqqd/.local/share/truckersmp-cli/wine-discord-ipc-bridge/winediscordipcbridge.exe']
Executables: None
Game Arguments: ['python3', '/home/fqqd/.local/share/truckersmp-cli/Proton/proton', 'run', '/home/fqqd/.local/lib/python3.11/site-packages/truckersmp_cli/truckersmp-cli.exe', '/home/fqqd/.local/share/truckersmp-cli/Euro Truck Simulator 2/data', '/home/fqqd/.local/share/truckersmp-cli/TruckersMP', '-rdevice', 'dx11', '-nointro', '-64bit']
Waiting time (early): 5
Waiting time: 0
Proton output:
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561199263902977 [API loaded no]
Fossilize INFO: Overriding serialization path: "/home/fqqd/.local/share/Steam/steamapps/shadercache/227300/fozpipelinesv6/steamapprun_pipeline_cache".
^C⏎ 
~~~
</details>

## Screenshots
<details><summary>Collapsed screenshots</summary>

![ets2mp_errpr](https://github.com/truckersmp-cli/truckersmp-cli/assets/96952506/f2a9b394-1cd5-4b4f-8aaa-daad6e44b290)

</details>

## Information
 - OS: CachyOS (Arch Linux)
 - Proton version: Proton version is (major=7, minor=0)
 - truckersmp-cli version: 0.9.1.1

## Additional context
I already tried updating everything and relogging into linux. Might have something to do with the Steam Beta, although I'm unsure as it worked just moments before the update.

**Comment by FQQD** [comment]
Trying to update again seems to have updated something, but didn't change anything

**Comment by linuxsdev** [comment]
I've got the same issue. Using Arch,

Everything worked fine two or three days ago. After the update it's broken.
Reinstall didn't work. 

Besides the "Euro Truck Simulator 2 can not access Steam client." Pop-Up the following messages are appearing in terminal:
![image](https://github.com/truckersmp-cli/truckersmp-cli/assets/39015775/d4edf8f3-fee4-44f0-a1e3-12e840adabeb)

**Comment by femrek** [comment]
The same in Fedora. I was able to play until last update. I checked for steam client update. I deleted truckersmp folder and reinstalled, still, it does not work.
![image](https://github.com/truckersmp-cli/truckersmp-cli/assets/29581978/8150ef75-d10b-4d8a-9daa-730f3c804a5f)

**Comment by Lucki** [comment]
Please have a look into your [prefix](https://github.com/truckersmp-cli/truckersmp-cli#wineprefix) in the `drive_c/Program Files (x86)/Steam/` folder and list which files are present with sha256sums.

Maybe try to backup the contents and copy the files from your native steam install `$XDG_DATA_HOME/Steam/legacycompat/` into the previously mentioned prefix folder.

**Comment by Dynamicwork** [comment]
I can confirm that I am having exactly same issue as described by @femrek despite the fresh reinstallation of truckersmp-cli and all related folders. Same issue occurs on atsmp too.

![Steamdir](https://github.com/truckersmp-cli/truckersmp-cli/assets/9463434/6854f2ca-8dde-45b6-be25-e871f009e54e)

@Lucki: I've printed a list of sha256 values of all files in the folder you mentioned. Did the same on both ETS2 and ATS subdirectories and got an identical result:

```
7ab92936ae339861e59bdeb690ad2f2948a126db073c1709fedcd6a441a9cadc  ./GameOverlayRenderer64.dll
3bc54ae2d65fffc2506a70f9551ccdc6c74a7bceb9f2c5522f8f80b2f5ffe5e4  ./steamclient64.dll
ff16620e7e45f6f2c1f588da5fdecef03856796828572f359f5fc892247ee989  ./steamclient.dll
b2000e57123e99bbbe26aaec40cfaf09a4df93959c5148f0db571ed2e3401102  ./Steam.dll
a12c6c9ed617bf7c804227cb494666487c9d185daf61940af498980f6937387e  ./steam.exe
895d3fe86007b73d1a0d0c8ebdf3ffda40c90cace3469f2d34d117bff37c9901  ./steamapps/libraryfolders.vdf
```

`./config` folder contained no files or subfolders.

**Comment by drizzo0** [comment]
Same issue here.
Installed truckersmp-cli yesterday for the first time on Kali (Debian 11)
Here the sha256:
`
8d8990fb04a6805e5d253628e790a3fcb3c1902ab868d3952143a09943a2648c  GameOverlayRenderer64.dll
8334c2f7650e5cc1596e06cb5da16367eb7d49f896a882bb9ce3872f321d7140  steamclient64.dll
afb09bae41a92dd356aa33e182be2de896b176e7b7cb37967b390e477a061fec  steamclient.dll
b2000e57123e99bbbe26aaec40cfaf09a4df93959c5148f0db571ed2e3401102  Steam.dll
a12c6c9ed617bf7c804227cb494666487c9d185daf61940af498980f6937387e  steam.exe
`
config folder is empty too

**Comment by rawfoxDE** [comment]
welp .. no fix yet ?
any idea about the reasons? .. ive also tried a lot .. SELinux maybe ?!?

**Comment by rawfoxDE** [comment]
> Maybe try to backup the contents and copy the files from your native steam install `$XDG_DATA_HOME/Steam/legacycompat/` into the previously mentioned prefix folder.

This did not help, same issue :/

**Comment by kallestrop** [comment]
I can reproduce this issue. ETS2/ATS won't start anymore with Proton Version 7 or older. You have to update your installation with truckersmp-cli like this:

'truckersmp-cli -n yoursteamname --proton-appid 2348590 update ets2'

Check in 'truckersmp-cli/Proton/version' if Proton version is '1684512816 proton-8.0-2d' 

After that, truckersmp-cli starts again without any issue

**Comment by drizzo0** [comment]
> I can reproduce this issue. ETS2/ATS won't start anymore with Proton Version 7 or older. You have to update your installation with truckersmp-cli like this:
> 
> `truckersmp-cli -n yoursteamname --proton-appid 2348590 update ets2`
> 
> Check in `truckersmp-cli/Proton/version` if Proton version is `1684512816 proton-8.0-2d`
> 
> After that, truckersmp-cli starts again without any issue

Thanks! It works but to update I had to run
`$HOME/.local/share/truckersmp-cli/steamcmd/steamcmd.sh +login <steamusername> +force_install_dir $HOME/.local/share/truckersmp-cli/Proton +app_update 2348590 validate +quit`
because `truckersmp-cli -n yoursteamname --proton-appid 2348590 update ets2` was throwing `Error! App '227300' state is 0x10C after update job.`

**Comment by rawfoxDE** [comment]
`$HOME/.local/share/truckersmp-cli/steamcmd/steamcmd.sh +login <steamusername> +force_install_dir $HOME/.local/share/truckersmp-cli/Proton +app_update 2348590 validate +quit`

This made it ! Have a ton of thanks :)

**Comment by kakurasan** [comment]
@kallestrop Thanks, updating my Proton fixed the issue. Proton users need to switch to the latest version.
* `proton-7.0-6e`: Not working
* `proton-8.0-2c`: Not working
* `proton-8.0-2d`: Working

**Comment by FQQD** [comment]
> 

yep, worked perfectly. thanks for all the help guys!
I'm not sure if i should close the issue though, as the default proton version hasn't been changed (i think)
Feel free to close the issue when this is completely resolved

**Comment by Tarballwalf** [comment]
Issue persists with proton experimental, installed via steam itself
