### ISSUE TITLE
Game wont start

### ISSUE THREAD

**Issue by sindney1001** [truckersmp-cli/truckersmp-cli#343]
[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
When I type "truckersmp-cli"  with or without any arguments I get an error.

## Expected behavior
Terminal -> "truckersmp-cli"

## Command
~~~
truckermp-cli -n [my name] start ets2mp
~~~

## Terminal output
<details><summary>Traceback (most recent call last):
  File "/usr/local/bin/truckersmp-cli", line 13, in <module>
    from truckersmp_cli.main import main
ModuleNotFoundError: No module named 'truckersmp_cli'
</summary>

</details>

## Information
 - OS: Ubuntu 23.04
 - Proton or Wine version: wine-8.0.2 and Proton 8.0
 - truckersmp-cli version: 0.10.1

**Comment by Lucki** [comment]
Please outline the steps you have taken for installation.

**Comment by sindney1001** [comment]
I don't remember the exact command but the game was working. This started just today.

**Comment by sindney1001** [comment]
Fixed by uninstalling truckersmp-cli and reinstalling with 
~~~
python3 -m pip install --user truckersmp-cli
~~~

**Comment by Lucki** [comment]
Thank you for sharing the solution :)
