### ISSUE TITLE
Terminal hangs when trying to launch game

### ISSUE THREAD

**Issue by sindney1001** [truckersmp-cli/truckersmp-cli#345]
---
name: Terminal hangs when trying to launch game
about: Game not working

---

[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
Terminal hangs and nothing happens unless I press CTRL + C

## Expected behavior
Game is expected to start.

## Command
~~~
truckersmp-cli -n myusername -vv start ets2mp
~~~

## Terminal output
<details><summary>j

~~~
jonni@jonni-System-Product-Name:~$ truckersmp-cli -n myusername -vv start ets2mp
** INFO **  Platform is Linux, using Proton
** INFO **  Log file: <empty> (Default)
** INFO **  Game directory: /home/jonni/.local/share/truckersmp-cli/Euro Truck Simulator 2/data (Default)
** INFO **  Prefix directory: /home/jonni/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix (Default)
** INFO **  Game options: -nointro -64bit (Default)
** INFO **  TruckersMP MOD directory: /home/jonni/.local/share/truckersmp-cli/TruckersMP (Default)
** INFO **  Whether to disable Steam Runtime (deprecated): False (Default)
** INFO **  Whether to disable Steam Runtime: False (Default)
** INFO **  Whether to use Flatpak version of Steam: False (Default)
** INFO **  Whether to disable Steam Overlay: False (Default)
** INFO **  Proton directory: /home/jonni/.local/share/truckersmp-cli/Proton (Default)
** INFO **  Steam Runtime directory: /home/jonni/.local/share/truckersmp-cli/SteamRuntime (Default)
** INFO **  Rendering backend: gl (Default)
** INFO **  AppID/GameID: 227300 (ets2)
** DEBUG **  Updating mod files
** DEBUG **  Creating directory /home/jonni/.local/share/truckersmp-cli/TruckersMP if it doesn't exist
** DEBUG **  No files to download
** INFO **  Proton version is (major=8, minor=0)
** INFO **  Using Steam Runtime container
~~~
</details>

## Screenshots
<details><summary>Collapsed screenshots</summary>

[comment]: # (If applicable, add screenshots to help explain your problem:)

</details>

## Information
 - OS: Ubuntu 23.10
 - Proton or Wine version: Wine 6.09, Proton 8
 - truckersmp-cli version: 0.10.1

## Additional context
This started after OS re-install. Before it was working fine.

**Comment by kallestrop** [comment]
Have you any  network share mounted with gvfs? If so, try to unmount them before execute truckersmp-cli.

I had the same issue in the past and couldn't find out why sometimes the starting process hangs at "Using Steam Runtime container". 

Until i noticed the interruption always occurs when i have a smb or nfs share mounted with gvfs. Fixed mounts in `fstab` are not affected. 

The not responding terminal output continued instantly after i unmounted the shares.

**Comment by Lucki** [comment]
Interesting, relevant is

https://github.com/truckersmp-cli/truckersmp-cli/blob/a5fc6df4ac498c1b454a9305db326467b2d0906f/truckersmp_cli/gamestarter.py#L55-L74

with three function call chains to the next logging:
* https://github.com/truckersmp-cli/truckersmp-cli/blob/a5fc6df4ac498c1b454a9305db326467b2d0906f/truckersmp_cli/utils.py#L324
* https://github.com/truckersmp-cli/truckersmp-cli/blob/a5fc6df4ac498c1b454a9305db326467b2d0906f/truckersmp_cli/utils.py#L256
* https://github.com/truckersmp-cli/truckersmp-cli/blob/a5fc6df4ac498c1b454a9305db326467b2d0906f/truckersmp_cli/utils.py#L811

`wait_for_steam()` seems somewhat obvious but need further debugging.

**Comment by Synthron** [comment]
same issue for me, but it seems that after some 20-odd minutes the game starts. It doesn't matter if I have steam already running or not, discord-ipc bridge disabled or enabled also doesn't change anything. 

It seems that truckersmp-cli is waiting for a specific task or state, but can't seem to find it in a timely manner

Command sent:
`truckersmp-cli start ets2mp -vv --without-wine-discord-ipc-bridge`

Output:
```** INFO **  Platform is Linux, using Proton
** INFO **  Log file: <empty> (Default)
** INFO **  Game directory: /home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/data (Default)
** INFO **  Prefix directory: /home/marco/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix (Default)
** INFO **  Game options: -nointro -64bit (Default)
** INFO **  TruckersMP MOD directory: /home/marco/.local/share/truckersmp-cli/TruckersMP (Default)
** INFO **  Whether to disable Steam Runtime (deprecated): False (Default)
** INFO **  Whether to disable Steam Runtime: False (Default)
** INFO **  Whether to use Flatpak version of Steam: False (Default)
** INFO **  Whether to disable Steam Overlay: False (Default)
** INFO **  Proton directory: /home/marco/.local/share/truckersmp-cli/Proton (Default)
** INFO **  Steam Runtime directory: /home/marco/.local/share/truckersmp-cli/SteamRuntime (Default)
** INFO **  Rendering backend: gl (Default)
** INFO **  AppID/GameID: 227300 (ets2)
** DEBUG **  Updating mod files
** DEBUG **  Creating directory /home/marco/.local/share/truckersmp-cli/TruckersMP if it doesn't exist
** DEBUG **  No files to download
** INFO **  Proton version is (major=8, minor=0)
** INFO **  Using Steam Runtime container
```

**Comment by Synthron** [comment]
I found out that the problematic function is `def find_discord_ipc_sockets()` in utils.py
Having discord installed from neither snap nor Flatpak seems to be an issue. I have installed the .deb packets from discord directly. 
It seems this function is then entering a loop and only exiting after timeout some 25 minutes later

**Comment by Synthron** [comment]
in `utils.py` on line 271 - 273 I set the recursive check to False like this:

```    return glob.glob(
        os.path.join(os.getenv("XDG_RUNTIME_DIR", "/tmp"), "**", "discord-ipc-*"),
        recursive=False)```

this fixed the issue for me, game now starts instantly and since I use the option `--without-wine-discord-ipc-bridge` the discord-ipc-bridge doesnt matter to me
