### ISSUE TITLE
I have ProMods files installed but not being detected by truckersmp-cli

### ISSUE THREAD

**Issue by vikingnope** [truckersmp-cli/truckersmp-cli#360]
[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug

I have the mod files installed in the correct directory as they work fine on the normal game version without truckersmp. When I go into truckersmp and select promods it says I do not have promods installed.

## Expected behavior

Should just work fine

## Command
~~~
truckersmp-cli --gamedir '/run/media/aiden/HDD 2/SteamLibrary/steamapps/common/Euro Truck Simulator 2' start ets2mp
~~~

## Terminal output
<details><summary>Collapsed log</summary>

~~~
Replace this line with the terminal output you're getting
when running the command with debug output [-vv]
~~~
</details>

## Screenshots
<details><summary>Collapsed screenshots</summary>

![image](https://github.com/truckersmp-cli/truckersmp-cli/assets/81376423/2b77af5d-d5b8-4ae2-8259-2e669bf043ea)

![image](https://github.com/truckersmp-cli/truckersmp-cli/assets/81376423/92c05ec4-2f06-4edd-9016-604202352a2b)

</details>

## Information
 - OS: Arch Linux latest
 - Proton or Wine version: Proton 9
 - truckersmp-cli version: 0.10.2

**Comment by vikingnope** [comment]
> Please use the [correct prefix](https://github.com/truckersmp-cli/truckersmp-cli?tab=readme-ov-file#singleplayer-mods-and-promods) or [specify your existing prefix](https://github.com/truckersmp-cli/truckersmp-cli?tab=readme-ov-file#using-a-different-prefix-location).

I have this now `truckersmp-cli --gamedir '/run/media/aiden/HDD 2/SteamLibrary/steamapps/common/Euro Truck Simulator 2' --prefixdir "/run/media/aiden/HDD 2/SteamLibrary/steamapps/compatdata/227300/pfx" start ets2mp`, still nothing

**Comment by Lucki** [comment]
From the README:
> While the prefix for Wine will point directly to the prefix location, Proton uses a subfolder pfx for the actual prefix and points to the parent folder.

**Comment by vikingnope** [comment]
Managed to fix the command thx :)

**Comment by Lucki** [comment]
Great :)
