### ISSUE TITLE
(Access Denied) SteamCMD exited abnormally

### ISSUE THREAD

**Issue by WoutvanderAa** [truckersmp-cli/truckersmp-cli#363]
hey guys.

I run the following command to update my game version: `truckersmp-cli -n wout2007 update`

But then I get the following:

Wout@fedora:~$ truckersmp-cli -n wout_2007  update
Redirecting stderr to '/home/Wout/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/Wout/.local/share/Steam/logs'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726605427
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 24.38 (157716044 / 647021625)
Success! App '1391110' fully installed.
Redirecting stderr to '/home/Wout/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/Wout/.local/share/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726605427
-- type 'quit' to exit --
Loading Steam API...OK
IPC function call IClientUtils::SetSpew took too long: 45 msec
Logging in using cached credentials.
Logging in user 'wout_2007' [U:1:1168406462] to Steam Public...FAILED (Access Denied)
SteamCMD exited abnormally

I am on game version 1.50.5 and I tried to set my game to the 1.51 beta on steam that the launcher says I need to update it to. I assume that it is asking me to update the second ets2 game installed (for truckersmp-cli)

fix: fixed the issue by saving my credentials.

**Comment by Lucki** [comment]
Your command user doesn't match the log file user.
It seems the credentials for the user `wout_2007` are outdated. Please verify this by logging in and remembering the credentials for this user in the normal steam client.

**Comment by WoutvanderAa** [comment]
> Your command user doesn't match the log file user. It seems the credentials for the user `wout_2007` are outdated. Please verify this by logging in and remembering the credentials for this user in the normal steam client.

thats that weird thing, when I run the command steam closes and I get this error. I am 100% sure that this is my username. Do I need to enter my password somewhere?

**Comment by Lucki** [comment]
It should ask for your password if the credentials aren't saved in your normal steam client.

**Comment by WoutvanderAa** [comment]
> It should ask for your password if the credentials aren't saved in your normal steam client.

They are not saved in my steam, and it does not ask for my password. Should I save my credentials in steam and try again?

**Comment by Lucki** [comment]
Do you mind sharing the solution?

**Comment by WoutvanderAa** [comment]
> Do you mind sharing the solution?

I saved my login credentials when logging in, this fixed the issue for me and I got a password promts to log in and update it.
